# Generated by Django 3.1.1 on 2020-09-29 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_productgroup_sub_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productgroup',
            old_name='sub_category',
            new_name='subcategory',
        ),
    ]
